version: '3.8'

services:
  app:
    build: 
      context: ./
      dockerfile: docker/app/Dockerfile
    command: python craft serve -p 8000 -b 0.0.0.0
    volumes:
      - ./:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - .env